# Generated by Django 5.0.7 on 2024-08-14 12:15

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用語名')),
                ('description', markdownx.models.MarkdownxField(verbose_name='説明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'ordering': ['order'],
                'permissions': [('can_edit_glossary', 'Can edit glossary terms')],
            },
        ),
    ]
